# sqp_f24fe3dc6557611d13db76f464be6b517c5eb5b4

default:
  image: maven:3.8.2-openjdk-11
  tags:
    - k8s

variables:
  M2_EXTRA_OPTIONS: "-s .m2/settings.xml"
  IMAGE_NAME: spring-petclinic
  TAG: $CI_COMMIT_SHA
  
stages:
  - check
  - build
  - sonarscan
  - push
  - dockerize
  - deploy

check-version:
  stage: check
  script:
    - mvn --version

build-job:
  stage: build
  script:
    - echo "Building the WAR file"
    - mvn package
    - ls -l target/*.war
  artifacts:
    paths:
      - target/
    expire_in: 1 week

sonarscan:
  stage: sonarscan
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" 
    SONAR_HOST_URL: http://174.138.104.191:9000
    SONAR_TOKEN: sqp_f24fe3dc6557611d13db76f464be6b517c5eb5b4
  image:
    name: sonarsource/sonar-scanner-cli:latest
  script:
   - sonar-scanner -Dsonar.qualitygate.wait=true

push-to-nexus:
  stage: push
  script:
    - mvn $M2_EXTRA_OPTIONS deploy

dockerize:
  stage: dockerize
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${USERNAME}" "${PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --destination "$USERNAME/$IMAGE_NAME:$TAG"

deploy-to-kubernetes:
  stage: deploy
  image: 
    name: kunchalavikram/kubectl_helm_cli:latest  # Helm
    entrypoint: [""]
  before_script:
    - mkdir -p ~/.kube
    - cat "$KUBECONFIG" > ~/.kube/config 
  script:
    - helm upgrade --install petclinic petclinic-chart/

