version: '2'

services:
  cli: 
    container_name: cli-demo
    build:
      context: .
      dockerfile: Dockerfile
    command: ["printer"]
    env_file: .env
    environment:
      TEST_ENV_ITEM: local