name: Release

on:
  workflow_dispatch:

jobs:
  config-release-file:
    name: Configure Release file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Nothing to do
        run: echo "Nothing to do"
