name: Submodules

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight.
  workflow_dispatch:

jobs:
  update-submodules:
    name: Update Submodules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: develop
          submodules: recursive

      - name: Configure Git
        run: |
          git config --global user.name "${{github.actor}}"
          git config --global user.email "${{github.actor}}@users.noreply.github.com"

      - name: Update Submodules
        run: |
          git submodule update --remote
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update submodules references."
            git push
          else
            echo "No changes to commit"
          fi